on: [ push, delete, create ]

# We want only one mirror workflow at a time.
concurrency:
  group: git-mirror-me

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror a git repository over SSH
        uses: agherzan/git-mirror-me-action@v1.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          destination-repository: "git@github.com:Scam-Scanner/ScamScanner.git"